### ISSUE TITLE
Shouldn't it be 1024? Or does gzip etc use the "new" standard?

### ISSUE THREAD

**Issue by VandeurenGlenn** [WickyNilliams/file-gauge#1]
https://github.com/WickyNilliams/file-gauge/blob/8d80b54a20ef02e1ecf7e1746f69bf5cf6cd81ce/index.js#L71C35-L71C39

**Comment by WickyNilliams** [comment]
Oh good call. I always get confused between kB and KB. I'll update

**Comment by WickyNilliams** [comment]
Fixed in `0.6.0`
