### ISSUE TITLE
Support multiple byteFormats

### ISSUE THREAD

**Issue by VandeurenGlenn** [WickyNilliams/file-gauge#2]
Supporting most formats isn't that much extra code and maybe useful in the future when JavaScript files become 1GB 😂 .
Should have some code somewhere, I'll make a PR if you want?

**Comment by WickyNilliams** [comment]
You mean instead of always showing KB?

How about a new `format` option which has possible values `"auto" | "KB" | "MB" `. Or something like that. Default it to auto, which chooses the most appropriate based on size. And the others force it to a consistent format

**Comment by VandeurenGlenn** [comment]
Indeed, just to support bigger files.

format option is also good idea, I'll make pr for the auto and then we can see from there?

**Comment by WickyNilliams** [comment]
Sounds good. Appreciate it!

**Comment by VandeurenGlenn** [comment]
closed as of #3
